<a href="https://colab.research.google.com/github/MAPeters101/A_Neagoie_PytorchForDeepLearningBootcamp_Section02/blob/master/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
# Get tensor back as Python int
scaler.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])


In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4547, 0.3560, 0.0251, 0.7132],
        [0.8912, 0.6468, 0.1941, 0.8788],
        [0.8745, 0.5874, 0.6197, 0.6622]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [21]:
torch.rand(3, 3)

tensor([[0.3206, 0.3649, 0.1478],
        [0.6767, 0.4813, 0.6185],
        [0.0190, 0.4132, 0.3404]])

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [27]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-27-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
torch.__version__

'2.6.0+cu124'

In [29]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [31]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

** Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9694, 0.7916, 0.9544, 0.9147],
        [0.6419, 0.8664, 0.6163, 0.3396],
        [0.8771, 0.2652, 0.9269, 0.6597]])

In [40]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [41]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9694, 0.7916, 0.9544, 0.9147],
        [0.6419, 0.8664, 0.6163, 0.3396],
        [0.8771, 0.2652, 0.9269, 0.6597]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication

In [42]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor + 100, tensor

(tensor([11, 12, 13]), tensor([101, 102, 103]), tensor([1, 2, 3]))

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [45]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10), torch.add(tensor, 10), torch.sub(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([-9, -8, -7]))

https://www.mathsisfun.com/algebra/matrix-multiplying.html

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication  (scalar multiplication)
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [53]:
torch.rand(3, 2)

tensor([[0.4374, 0.8158],
        [0.1545, 0.3787],
        [0.0451, 0.2745]])

In [55]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))  # Will produce an error.

In [56]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6157, 0.5014],
        [1.0214, 0.8955]])

In [57]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.5223, 0.3880, 0.4208],
        [0.4616, 0.3417, 0.3688],
        [0.4348, 0.3156, 0.3308]])

In [58]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[3.5819, 2.5984, 2.2584],
        [4.3400, 3.3149, 2.8699],
        [2.7515, 1.7980, 1.5891]])

In [59]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10))

tensor([[2.7299, 3.3133, 1.0048, 2.7656, 2.1180, 2.9122, 2.4284, 2.4933, 2.6220,
         2.3951],
        [1.9315, 2.0151, 0.4170, 1.8262, 2.2900, 1.7750, 1.8049, 1.5606, 2.0894,
         1.9197],
        [2.2046, 2.7232, 0.9300, 2.0983, 2.1138, 2.3369, 2.1260, 2.0344, 1.8347,
         2.3713],
        [2.9022, 3.1483, 1.2723, 2.6515, 2.6190, 3.1791, 2.5442, 2.7854, 2.4751,
         2.4282],
        [2.7433, 4.1252, 1.2082, 2.8540, 3.5736, 3.1463, 2.7595, 3.1170, 3.1945,
         2.6861],
        [2.0778, 2.3267, 0.8216, 2.2145, 2.7106, 2.0676, 2.3686, 1.6365, 2.6162,
         2.0486],
        [3.2218, 3.5126, 1.1189, 3.0844, 3.1904, 3.2097, 2.7422, 2.9762, 3.0446,
         2.5282],
        [2.7727, 2.4866, 1.0592, 2.7026, 2.9365, 2.6193, 2.8393, 2.3018, 3.0700,
         2.2990],
        [2.7159, 2.5508, 1.3619, 2.2126, 2.3552, 2.7131, 2.1730, 2.2369, 2.2352,
         2.1207],
        [2.3751, 3.3554, 1.6148, 2.5693, 2.3948, 3.2526, 2.5072, 2.8245, 2.5974,
         2.1551]])

In [60]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [46]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [47]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [48]:
tensor @ tensor

tensor(14)

In [49]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [50]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 2.92 ms


In [51]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 413 µs, sys: 0 ns, total: 413 µs
Wall time: 685 µs


tensor(14)

In [52]:
### One of the most common errors in deep learning: shape errors

http://matrixmultiplication.xyz/

In [61]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [62]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [65]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [66]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [67]:
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [68]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [69]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
