<a href="https://colab.research.google.com/github/MAPeters101/A_Neagoie_PytorchForDeepLearningBootcamp_Section02/blob/master/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])


In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0830, 0.5870, 0.4253, 0.3614],
        [0.8041, 0.7652, 0.4499, 0.0659],
        [0.3885, 0.5949, 0.6011, 0.9926]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [20]:
torch.rand(3, 3)

tensor([[0.5839, 0.7502, 0.5256],
        [0.9832, 0.5292, 0.8002],
        [0.9806, 0.8622, 0.7984]])

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [26]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-26-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
torch.__version__

'2.6.0+cu124'

In [28]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

** Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2131, 0.5235, 0.4583, 0.0545],
        [0.3269, 0.3917, 0.8160, 0.2395],
        [0.6156, 0.6081, 0.3581, 0.3625]])

In [39]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [40]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2131, 0.5235, 0.4583, 0.0545],
        [0.3269, 0.3917, 0.8160, 0.2395],
        [0.6156, 0.6081, 0.3581, 0.3625]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication

In [41]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor + 100, tensor

(tensor([11, 12, 13]), tensor([101, 102, 103]), tensor([1, 2, 3]))

In [42]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10), torch.add(tensor, 10), torch.sub(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([-9, -8, -7]))

https://www.mathsisfun.com/algebra/matrix-multiplying.html

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication  (scalar multiplication)
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [45]:
torch.rand(3, 2)

tensor([[0.1399, 0.7177],
        [0.2761, 0.8008],
        [0.2345, 0.5812]])

In [46]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))  # Will produce an error.

In [47]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.5864, 1.0620],
        [0.1205, 0.4066]])

In [48]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.4839, 0.5823, 0.6389],
        [0.9114, 0.9216, 0.9137],
        [0.4426, 0.4991, 0.5291]])

In [49]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[1.8442, 2.5318, 3.0910],
        [1.2823, 1.8482, 2.3961],
        [2.0118, 2.8586, 2.9290]])

In [50]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10))

tensor([[2.7915, 3.8344, 3.4990, 1.8742, 3.0220, 2.1701, 2.0174, 4.4109, 1.7951,
         2.6815],
        [3.1654, 3.5159, 2.9643, 2.1263, 2.9144, 2.0313, 1.5850, 3.9142, 1.4197,
         3.1420],
        [2.4616, 2.6150, 2.7425, 1.6031, 2.4745, 1.9691, 1.3375, 3.1782, 1.4944,
         2.4146],
        [3.6596, 3.4445, 4.1906, 2.0942, 3.6019, 2.1782, 2.3600, 4.2345, 2.5184,
         3.2857],
        [2.5072, 2.7662, 2.9935, 1.4898, 2.5556, 1.6888, 1.6437, 3.5085, 1.6002,
         2.2617],
        [3.4594, 3.9847, 3.9315, 2.2752, 3.5547, 2.5111, 2.2740, 4.4404, 2.2822,
         3.4754],
        [3.2898, 3.2317, 3.7933, 2.6027, 3.0397, 2.2392, 1.5490, 4.2044, 1.9258,
         3.1247],
        [2.7173, 2.2464, 2.8119, 1.7528, 2.6248, 1.7651, 1.4131, 2.6256, 1.7998,
         2.8815],
        [3.1145, 3.4850, 3.2994, 2.3880, 2.7253, 2.2619, 1.4602, 4.2572, 1.5085,
         2.9487],
        [3.3700, 3.4406, 3.3330, 2.4236, 3.3124, 2.2000, 1.5915, 4.0217, 1.9756,
         2.8182]])

In [51]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [52]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [53]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [54]:
tensor @ tensor

tensor(14)

In [55]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [56]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.42 ms, sys: 0 ns, total: 1.42 ms
Wall time: 1.97 ms


In [57]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 563 µs, sys: 0 ns, total: 563 µs
Wall time: 766 µs


tensor(14)

In [58]:
### One of the most common errors in deep learning: shape errors

http://matrixmultiplication.xyz/

In [60]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T)


In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

In [ ]:
## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean - note: the torch.mean() function require a tensor of float32 to work
# torch.mean(x)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

## Finding the positional min and max

In [ ]:
x

In [ ]:
# Find the position in tensor that has the minimum value with argmin -> returns index position of target tensor where the minimum value occurs
x.argmin()

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

In [ ]:
x[9]

## Rehaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain wau

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

In [62]:
# Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

NameError: name 'x' is not defined

In [71]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [72]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [77]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [83]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [86]:
# torch unssqueeze() - adds a single dimension to a target at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Remove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [79]:
x_reshaped.shape

torch.Size([1, 9])

In [81]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [82]:
x_reshaped.squeeze().shape

torch.Size([9])