<a href="https://colab.research.google.com/github/MAPeters101/A_Neagoie_PytorchForDeepLearningBootcamp_Section02/blob/master/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# Get tensor back as Python int
scaler.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])


In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3181, 0.4646, 0.4693, 0.1566],
        [0.6136, 0.5209, 0.6758, 0.7119],
        [0.6800, 0.8549, 0.4342, 0.3074]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(3, 3)

tensor([[0.2005, 0.4939, 0.9726],
        [0.7944, 0.8114, 0.8624],
        [0.6610, 0.8046, 0.4239]])

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-26-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.__version__

'2.6.0+cu124'

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

** Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7750, 0.6399, 0.5153, 0.1830],
        [0.4110, 0.9629, 0.3919, 0.1608],
        [0.0750, 0.5266, 0.4673, 0.1425]])

In [ ]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7750, 0.6399, 0.5153, 0.1830],
        [0.4110, 0.9629, 0.3919, 0.1608],
        [0.0750, 0.5266, 0.4673, 0.1425]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor + 100, tensor

(tensor([11, 12, 13]), tensor([101, 102, 103]), tensor([1, 2, 3]))

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10), torch.add(tensor, 10), torch.sub(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([-9, -8, -7]))

https://www.mathsisfun.com/algebra/matrix-multiplying.html

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication  (scalar multiplication)
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [ ]:
torch.rand(3, 2)

tensor([[0.0723, 0.3721],
        [0.8143, 0.5703],
        [0.2093, 0.3444]])

In [ ]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))  # Will produce an error.

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.5404, 0.7426],
        [0.5933, 0.5460]])

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.8065, 0.7650, 0.9477],
        [0.1901, 0.2346, 0.2966],
        [0.4217, 0.4366, 0.5448]])

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[1.5846, 2.1825, 1.3503],
        [3.0661, 2.6828, 2.0574],
        [2.9991, 2.6765, 1.9708]])

In [ ]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10))

tensor([[2.8432, 3.2390, 3.0315, 3.4309, 3.9474, 2.6804, 3.0279, 3.0883, 3.5273,
         2.9035],
        [2.5513, 3.2681, 3.0956, 3.3656, 3.7568, 2.8746, 3.1648, 2.8259, 3.8238,
         2.6765],
        [1.6387, 2.2415, 2.7683, 2.4131, 2.5845, 2.0563, 2.5895, 2.4147, 2.5574,
         1.9865],
        [1.7239, 2.2603, 2.1440, 2.2665, 2.3729, 1.6678, 2.3229, 2.1127, 1.8977,
         1.5057],
        [1.8498, 2.4807, 2.8291, 3.2580, 2.7218, 1.6491, 2.3909, 2.5446, 2.6228,
         2.1269],
        [1.8686, 2.3778, 2.1902, 2.9647, 2.8995, 1.1665, 1.8039, 2.0347, 2.9944,
         2.5892],
        [1.9460, 2.9299, 2.2424, 2.9135, 2.9087, 2.1470, 2.6649, 2.5447, 2.4929,
         1.9242],
        [1.8907, 2.3584, 2.0628, 2.4628, 2.9234, 1.7985, 1.9154, 2.0542, 2.2148,
         1.9681],
        [2.2977, 3.7510, 3.7734, 4.4213, 3.6952, 2.6355, 3.6164, 3.5686, 3.8055,
         2.7668],
        [1.8318, 2.6523, 2.7963, 2.7313, 2.9733, 2.3326, 2.6945, 2.4676, 2.7918,
         1.9633]])

In [ ]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 571 µs, sys: 939 µs, total: 1.51 ms
Wall time: 1.83 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 484 µs, sys: 76 µs, total: 560 µs
Wall time: 679 µs


tensor(14)

In [ ]:
### One of the most common errors in deep learning: shape errors

http://matrixmultiplication.xyz/

In [ ]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
#torch.matmul(tensor_A, tensor_B)


In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function require a tensor of float32 to work
# torch.mean(x)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Rehaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain wau

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# torch unssqueeze() - adds a single dimension to a target at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Remove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [1]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape



(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [4]:
x[0,0]

tensor([1, 2, 3])

In [5]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [6]:
x[0][0][1]

tensor(2)

In [7]:
#x[1][1][1]

In [8]:
x[0][1][1]

tensor(5)

In [9]:
x[0][2][2]

tensor(9)

In [10]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [11]:
# Get all values of 0th and 1st dimension but onlyindex 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [15]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [13]:
x[0][1][1]

tensor(5)

In [16]:
x[0,1,1]

tensor(5)

In [17]:
# Get index 0 of oth and 1st dimension and all values of 2nd dimension
x[0, 0,:]

tensor([1, 2, 3])

In [19]:
x[0][0]

tensor([1, 2, 3])

In [20]:
# Index on x to return 9
x[:,2,2]

tensor([9])

In [21]:
# Index 0n x to return 3, 6, 9
x[0,:,2]

tensor([3, 6, 9])

In [23]:
# Index on x to return 9
print(x[0][2][2])

# Index 0n x to return 3, 6, 9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [24]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [25]:
array.dtype

dtype('float64')

In [26]:
tensor.dtype

torch.float64

In [27]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [28]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [29]:
tensor.dtype

torch.float32

In [30]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [31]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [32]:
numpy_tensor.dtype

dtype('float32')

In [33]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
  Start with random numbers -> tensor operations -> update random numbers to try and make them better repreentations of the data -> again -> again -> again...`

  To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

  Essentually what the random seed does is "flavour" the randomness.



In [37]:
torch.rand(3,3)


tensor([[0.9748, 0.0179, 0.3599],
        [0.6108, 0.9696, 0.6001],
        [0.8550, 0.6144, 0.0196]])

In [39]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7905, 0.6291, 0.2397, 0.0440],
        [0.2289, 0.1737, 0.5767, 0.4660],
        [0.3955, 0.0338, 0.4317, 0.6424]])
tensor([[0.9663, 0.7982, 0.3935, 0.2888],
        [0.5690, 0.8339, 0.2088, 0.8711],
        [0.0477, 0.7562, 0.5724, 0.2249]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
